const RECORDS = [
 {folder:"master-trainer",title:"Pembangunan Platform Micro Credential, Politeknik Port Dickson 2023",type:"Final implementation report",status:"VERIFIED",role:"Master Trainer; Ketua Penyelaras Pembangunan Platform MC",note:"Report records 42 lecturers, 18 expert panels / course platforms, Series 1 on 6 July, Series 2 on 3-4 August, review on 15 November and 15 December 2023.",url:"https://drive.google.com/file/d/1VqILVuQDkMbhrcqAabqBeuO59baD9r5a/view"},
 {folder:"master-trainer",title:"Master Trainer nomination / platform preparation",type:"Nomination document",status:"SOURCE FOUND",role:"Master Trainer",note:"Supporting appointment/nomination source located in Google Drive.",url:"https://drive.google.com/file/d/1zQpFvM-m_UiT4GNPlNm4UOMwhuMOqqv2/view"},
 {folder:"master-trainer",title:"Kertas Kerja MC 2023",type:"Signed programme working paper",status:"SOURCE FOUND",role:"Programme planning / coordination",note:"Signed 2023 working paper located in Drive.",url:"https://drive.google.com/file/d/10KosOEK-QQKWSOP78eBed8iLi_hOQ9AH/view"},
 {folder:"thunkable",title:"Kursus Pembangunan Apps Menggunakan Aplikasi Thunkable",type:"Speaker record",status:"VERIFIED",role:"Penceramah",note:"PSH programme, 14 June 2023, 8.00 am-5.00 pm. ULPL 2000655.",url:"https://drive.google.com/file/d/1VeZ9K85FTKnuKlSAXja0t5nSfqBfFyvd/view"},
 {folder:"thunkable",title:"Thunkable workshop photographs",type:"Authentic 2023 photographs",status:"VERIFIED VISUAL",role:"Speaker / facilitator",note:"Two Drive photographs are embedded directly in this chapter.",url:""},
 {folder:"camp21",title:"Appointment as Speaker and Facilitator - CAMP21: Synergizing Literacies 2023",type:"Official appointment + Terms of Reference",status:"VERIFIED",role:"Lead DT Facilitator",note:"25-27 September 2023. Official TOR assigns facilitator task distribution, monitoring and support to the Lead DT Trainer.",url:"https://drive.google.com/file/d/1o_1LjjrBFe1NYEcnH3_rJAIlKezPx0Zd/view"},
 {folder:"camp21",title:"CAMP21 2023 Certificate of Appreciation",type:"Certificate",status:"VERIFIED",role:"Design Thinking Facilitator",note:"Certificate for CAMP21 Synergising Literacies 2023, 25-27 September 2023.",url:"https://drive.google.com/file/d/17-Zee0GI9y6rsiwoZbh1xPXVsMYFzRIM/view"},
 {folder:"publication",title:"Community Involvement in an English Classroom of a TVET Institution in Malaysia",type:"Published proceedings paper",status:"VERIFIED",role:"Co-author",note:"Susan S Magallanes and Julie Marlina Hasan. AIJR Proceedings, 2023. DOI: 10.21467/proceedings.151.49.",url:"https://drive.google.com/file/d/168LMbuHp8_GsQfjmURPfJ4Uux4vMcRxS/view"},
 {folder:"respex",title:"Sumbangan RESPEx 2023",type:"Contribution record",status:"SOURCE FOUND",role:"Exact Julie-specific scope to verify",note:"Dedicated contribution evidence is present in Drive; keep the role wording conservative until the source is fully extracted.",url:"https://drive.google.com/file/d/1Tj2DG0Bf-F9RuTYiT2163Ai_nhrsYp2n/view"},
 {folder:"ukkp",title:"JK Audit NIOSH - October 2023",type:"Institutional committee evidence",status:"SOURCE FOUND",role:"Committee contribution - exact wording to verify",note:"2023 UKKP folder and October NIOSH audit document found in Drive.",url:"https://drive.google.com/file/d/1JMtXhkWwyxtTPQxWRtfpTksupgdkD9HE/view"},
 {folder:"rakan-muda",title:"Surat Pelantikan JK Rakan Muda Ramadan 2023",type:"Official appointment letter",status:"SOURCE FOUND",role:"Committee member - exact portfolio wording to verify",note:"Official 2023 appointment letter located in Drive.",url:"https://drive.google.com/file/d/1vB0ubmtQKWRs5brccOo8KsIkn_A623UH/view"},
 {folder:"csr",title:"CSR Ostrich Farm - March 2023",type:"CSR record",status:"SOURCE FOUND",role:"Exact role to verify",note:"March 2023 CSR record located in Drive.",url:"https://drive.google.com/file/d/1kBuAaS3s7amUQOzLwHZFvweWRAFADg63/view"}
];
const views=["home","about","journey","work","dh13","evidence"];
function route(){const raw=location.hash.replace(/^#\/?/,"")||"home";const [name,sub]=raw.split("/");const active=views.includes(name)?name:"home";document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));document.getElementById("view-"+active)?.classList.add("active");if(active==="journey"&&sub==="dh12-transition")setTimeout(()=>document.getElementById("dh12-transition")?.scrollIntoView({behavior:"smooth"}),50)}
addEventListener("hashchange",route);
const drawer=document.getElementById("drawer"),drawerTitle=document.getElementById("drawer-title"),drawerBody=document.getElementById("drawer-body");document.getElementById("close").onclick=()=>drawer.close();
function openFolder(folder){let rows=RECORDS.filter(r=>r.folder===folder);if(folder==="service")rows=RECORDS.filter(r=>["ukkp","rakan-muda","csr"].includes(r.folder));drawerTitle.textContent=(folder||"2023 EVIDENCE").replaceAll("-"," ").toUpperCase();drawerBody.innerHTML=rows.length?rows.map(r=>`<div class="drawer-record"><span class="status ${r.status.includes('VERIFIED')?'verified':''}">${r.status}</span><h4>${r.title}</h4><p><strong>Evidence type:</strong> ${r.type}</p><p><strong>Role:</strong> ${r.role}</p><p>${r.note}</p>${r.url?`<a class="btn" target="_blank" rel="noopener" href="${r.url}">Open source in Google Drive →</a>`:`<div class="drawer-placeholder">The visual evidence is embedded in this page.</div>`}</div>`).join(""):`<p>No 2023 record connected to this folder yet.</p>`;drawer.showModal()}
document.querySelectorAll("[data-folder]").forEach(el=>el.addEventListener("click",()=>openFolder(el.dataset.folder)));document.querySelectorAll("[data-jump]").forEach(el=>el.addEventListener("click",()=>document.getElementById(el.dataset.jump)?.scrollIntoView({behavior:"smooth"})));document.querySelector(".open-year-map")?.addEventListener("click",()=>document.getElementById("shift")?.scrollIntoView({behavior:"smooth"}));
function renderMasterEvidence(){const box=document.getElementById("records");if(!box)return;box.innerHTML=RECORDS.map(r=>`<article><span class="badge-lime">2023</span><h3>${r.title}</h3><p>${r.type}</p><button class="btn" data-master-folder="${r.folder}">Inspect →</button></article>`).join("");box.querySelectorAll("[data-master-folder]").forEach(b=>b.onclick=()=>openFolder(b.dataset.masterFolder))}
document.addEventListener("DOMContentLoaded",()=>{route();renderMasterEvidence()});
