(() => {
'use strict';
const e=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={pdp:'Teaching & Learning',rdci:'Innovation, Research & Publication',lead:'Leadership',diri:'Professional Development',sumb:'Contribution & Service'};
const crit=r=>labels[r.domain]||labels.lead;
const sheet='https://docs.google.com/spreadsheets/d/1xMLJuOartI7gxrbwgwnC8KNAQ2Cr8xVd8RP-3HxcjeA/edit';
const domains={master:'training','master-trainer':'training',thunkable:'training',camp21:'training',publication:'research',respex:'community',ukkp:'leadership','rakan-muda':'community',csr:'community',panasonic:'training',international:'community',sharing:'training','leadership-service':'leadership',community:'community',training:'training',dh12:'leadership'};
let contributions=[], paused=false;
const card=r=>`<a class="feature-card" href="#/contribution/${r.key}"><div class="feature-media" style="background:${r.color||'#00E0BA'}">${r.photos?.length?`<img src="${e(r.photos[0].src)}" alt="${e(r.photos[0].caption)}" loading="lazy">`:`<div class="type-art" aria-hidden="true">${e(crit(r).split(/,| & /)[0])}<br>↗</div>`}</div><div class="feature-copy"><span class="tag">${e(r.year)}</span><span class="kicker">${e(crit(r))}</span><h3>${e(r.title)}</h3><p>${e(r.role)}</p><small>Explore contribution ↗</small></div></a>`;
const footer=`<footer class="global-footer"><div><strong>JULIE MARLINA HASAN</strong><br>Lecturer · Trainer · Digital learning creator<br>Politeknik Port Dickson</div><nav><a href="#/about">About</a><a href="#/journey">Journey</a><a href="folio-dh13.html">Folio DH13</a><a href="#/evidence">Evidence</a><a href="#/contact">Collaborate</a></nav><button class="motion-toggle" aria-pressed="false">Pause motion</button></footer>`;
function chapter2025(){const root=document.getElementById('chapter-2025').shadowRoot;if(!root)return;
root.querySelectorAll('.case').forEach((s,i)=>{const a=s.querySelector('a[href^="https://drive.google.com"]');const id=s.id;if(id==='hakiki')return;const title=({tecc:'TECC · Learning-space evolution',linkedin:'LinkedIn Basics · Career readiness',tvet:'Eksplorasi TVET Madani @ PPD',respex:'RESPEx25 · Programme-book contribution'})[id]||s.querySelector('h2')?.textContent.trim().replace(/\s+/g,' ')||'2025 contribution';contributions.push({key:'y25-'+id,year:'2025',title,role:s.querySelector('.role')?.textContent.replace(/\s+/g,' ').replace('MY ROLE / WORKING RECORD','').trim()||'Contribution record — exact role follows evidence',note:s.querySelector('.copy')?.textContent||s.querySelector('p:not(.eyebrow)')?.textContent||'See the connected source for contribution details.',url:a?.href||'',status:a?'Source located — validation pending':'Working chapter — supporting evidence pending',domain:({tecc:'teaching',linkedin:'training',tvet:'training',respex:'community',develop:'training',contribute:'leadership',recognition:'leadership',hakiki:'leadership'})[id]||'leadership',photos:[],color:'#DBFF3D'});});
root.querySelectorAll('.photo-collage,.programme-collage,.collage-gallery').forEach(s=>{if(!s.querySelector('img'))s.hidden=true;});
root.querySelectorAll('.photo-slot').forEach(s=>s.hidden=true);
root.querySelectorAll('section').forEach(s=>{const heading=[...s.querySelectorAll('h2,h3')].find(h=>h.textContent==='Moments that matter.');if(heading&&!s.querySelector('img'))heading.remove();});
const css=document.createElement('style');css.textContent=`:host{background:#faf9f6;font-family:Arial,sans-serif}section{padding:65px 6vw}h2{font-size:clamp(40px,6vw,86px);line-height:.98}h3{font:800 22px/1.2 Arial}.hero{min-height:0;padding:70px 6vw}.hero h1{font-size:clamp(75px,12vw,160px)}.orbit{opacity:.2}.case{min-height:0;border-color:#ddd}.case:after{display:none}.role{font-size:16px;padding:15px 20px}.folder,.card-holder{box-shadow:none;border:1px solid #ddd}.photo-slot[hidden]{display:none!important}.photo-frame:not(.loaded){display:none}.photo-collage:has(.photo-frame:not(.loaded)){display:none}.gallery-editor,.photo-edit-tools{display:none}.lead{font-size:24px}.copy{font-size:17px}.tile{border:1px solid #ddd}.pill{border:0;background:#323EDD}.section-nav{background:#17171b}.holder-toggle{font-size:12px}.photo-lightbox{border:0}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}`;
root.append(css);const minor=root.getElementById('contribute');if(minor){const d=document.createElement('details');d.className='minor-register';d.innerHTML='<summary style="font-weight:800;cursor:pointer;padding:18px">More 2025 contributions</summary>';minor.replaceWith(d);d.append(minor);}root.querySelector('footer')?.remove();
}
function enhance2026(){const root=document.getElementById('chapter-2026').shadowRoot;if(!root)return;
const roles=root.getElementById('roles'),evidence=root.getElementById('evidence');evidence.before(roles);
const css=document.createElement('style');css.textContent=`:host{--yellow:#FFCF00;--blue:#323EDD;--pink:#FF3483;--purple:#91008D;--teal:#00E0BA;--lime:#DBFF3D;background:#faf9f6}.hero{padding:65px 6vw}.hero h1{font-size:clamp(70px,10vw,150px)}.stack-card:last-child{height:185px;padding:22px}.stack-card strong{font-size:32px;line-height:1.05}.stack-card{border:0;box-shadow:0 8px 25px #1112}.intro{background:#fff;color:#17171b}.intro h2{color:#323EDD}.pillar{border-color:#ddd}section{padding:65px 6vw}h2{font-size:clamp(40px,6vw,86px)}.cyan,.pink{background:#faf9f6}.blue{background:#fff;color:#17171b}.pill{background:#323EDD;color:#fff;border:0}.facts span{border-color:#aaa}.collage figure,figure{border:0;box-shadow:0 4px 20px #1111}.collage figure{transform:none!important}.holder{background:white!important;border:1px solid #ddd;border-radius:16px;box-shadow:none;min-height:240px;padding:25px}.holder:before,.holder:after{display:none}.holder h3{margin-top:22px;font:800 24px/1.15 Arial}.holder small{color:#555}.cards{gap:20px}.filters button{border:1px solid #ddd}.filters button[aria-pressed=true]{background:#323EDD;color:white}.chapter-nav{top:114px}.ticker div{animation-duration:45s}.vault{background:#91008D}.archive{grid-template-columns:repeat(2,1fr);gap:30px 20px;margin-top:45px}.archive details{position:relative;background:#DBFF3D;color:#17171b;border:0;border-radius:0 15px 15px 15px;padding:24px;align-self:start}.archive details:before{content:'';position:absolute;top:-14px;left:0;width:40%;height:14px;border-radius:10px 10px 0 0;background:inherit}.archive a{color:#323EDD}.foot{display:none}.slot{display:none}.notice,#export-gallery{display:none}dialog{border:0}dialog .collage:empty{display:none}@media(max-width:650px){.archive{grid-template-columns:1fr}.chapter-nav{top:68px}.cards{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}`;
root.append(css);
// Use shareable programme pages for roles instead of modal-only routes.
root.addEventListener('click',evt=>{const b=evt.target.closest('[data-open]');if(b){evt.stopImmediatePropagation();location.hash='#/contribution/y26-'+b.dataset.open;}},true);
root.getElementById('gallery')?.remove();const galleryJump=root.querySelector('[data-jump=gallery]');if(galleryJump){galleryJump.dataset.jump='community';galleryJump.textContent='Photos';}root.querySelector('.hero button').dataset.jump='practice';root.querySelector('.hero button').textContent='Explore selected stories ↓';
const ticker=root.querySelector('.ticker');if(ticker){const b=document.createElement('button');b.textContent='Pause ribbon';b.style.cssText='margin:8px 6vw;padding:6px 13px;background:#DBFF3D;border:0;border-radius:20px';b.setAttribute('aria-pressed','false');b.onclick=()=>{const p=b.getAttribute('aria-pressed')!=='true';ticker.querySelector('div').style.animationPlayState=p?'paused':'running';b.setAttribute('aria-pressed',String(p));b.textContent=p?'Play ribbon':'Pause ribbon';};ticker.append(b);}
}
function init(){
 const nav=document.querySelector('.global-nav');nav.innerHTML=`<a class="logo" href="#/home"><b>JM</b> JULIE MARLINA.</a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav">Menu</button><nav id="main-nav" aria-label="Main navigation"><a href="#/home">Home</a><a href="#/journey">My Journey</a><a class="folio-link" href="folio-dh13.html">Folio DH13</a><a href="#/evidence">Evidence</a><a href="#/contact">Let’s Collaborate ↗</a></nav>`;
 nav.querySelector('.menu-toggle').onclick=function(){const open=this.getAttribute('aria-expanded')!=='true';this.setAttribute('aria-expanded',String(open));nav.querySelector('nav').classList.toggle('is-open',open);};
 const getphotos=r=>r.folder==='thunkable'?[{src:'assets/thunkable-01.jpg',caption:'Thunkable workshop · 2023'},{src:'assets/thunkable-02.jpg',caption:'Workshop participation · 2023'}]:r.folder==='master-trainer'?[{src:'assets/microcredential-report-photo.png',caption:'Authentic evidence from the 2023 implementation report'}]:r.folder==='camp21'?[{src:'assets/camp21-logo.png',caption:'CAMP21 programme identity · not a session photograph'}]:[];
 const old=RECORDS.filter(r=>r.year!=='2026');old.forEach((r,i)=>contributions.push({...r,key:'legacy-'+i,year:r.year||'2023',domain:domains[r.folder]||'leadership',photos:getphotos(r),color:['#FFCF00','#00E0BA','#DBFF3D'][i%3]}));
 PROGRAMMES_2026.forEach(r=>contributions.push({...r,key:'y26-'+r.id,year:'2026',url:r.source,domain:r.id==='role-14'?'research':r.group==='national'?(r.id==='role-13'?'research':'innovation'):r.group,photos:r.photos}));
 contributions.push({key:'smart-muet',year:'2026',title:'Smart MUET Guide V2',role:'Project Leader / Principal Research Officer',date:'7 September 2026 · confirmation letter',note:'Signed confirmation letter names Julie as Project Leader / Principal Research Officer, with Angela Kwon Mei Jun and Nurfarizah binti Ishak as researchers.',url:'https://drive.google.com/file/d/1JB6MvSUzXvDz8NVeJ-7DdNMgIlfv7eOQ/view',domain:'innovation',status:'Confirmation letter',photos:[],related:'https://juliemarlina-collab.github.io/Smart-MUET-v2/'});
 contributions.push({key:'gemini-webinar',year:'2026',title:'POLYCC Future-Ready AI Series',role:'Panel speaker · Gemini App & Gemini Notebook for teaching',date:'26 August 2026',note:'Appointed panel speaker for the BIPD POLYCC Future-Ready AI Series on using Gemini App and Gemini Notebook in teaching.',url:'https://drive.google.com/file/d/1ZSke0_1gE7JwYOFyWhs8CjcHokixEtVy/view',domain:'training',status:'Appointment',photos:[]});
 chapter2025();enhance2026();
 contributions.forEach(r=>{r.domain=window.JM_CRIT?JM_CRIT(r):r.domain});
 if(!window.JM_EDIT)contributions=contributions.filter(r=>!r.draft&&!/pending|working chapter/i.test(r.status||''));
 document.querySelectorAll('.share2023 .story-facts,.share2023 .date-rail,.share2024 .plan-visual').forEach(x=>{const d=document.createElement('details');d.className='evidence-extract';d.innerHTML='<summary>Read contribution details & supporting facts</summary>';x.replaceWith(d);d.append(x);});
 const portrait=document.querySelector('.threshold-visual');if(portrait)portrait.insertAdjacentHTML('beforeend','<img class="archive-portrait" src="assets/julie-camp21.jpg" alt="Julie facilitating · archive portrait"><small>Julie at work · archive portrait</small>');
 const journey=document.getElementById('view-journey');journey.insertAdjacentHTML('afterbegin',`<div id="journey-overview" class="studio-section"><p class="kicker">MY JOURNEY / THE WORK IN CONTEXT</p><h1 style="font-size:clamp(55px,8vw,110px)">GROWING THROUGH<br>THE WORK.</h1><p class="lead">From sharing classroom practice to wider professional responsibility, educator development and connected digital learning.</p><div class="year-grid">${[['2023','Share','Training, facilitation and scholarship.'],['2024','Step Up','The DH12 chapter begins; industry and institutional responsibilities widen.'],['2025','Expand','A wider professional network and evolving learning spaces.'],['2026','Converge & Build','Teaching, leadership, research and community contribution come together.']].map(r=>`<a class="year-tile" href="#/journey/${r[0]}"><b>${r[0]}</b><strong>${r[1]}</strong><p>${r[2]}</p><span>Explore chapter ↗</span></a>`).join('')}</div><p style="margin-top:35px"><a class="btn" href="#/dh13">Open DH13 synthesis ↗</a></p></div>`);
 document.getElementById('view-home').className='view';document.getElementById('view-home').innerHTML=`<header class="studio-hero"><div><p class="kicker">EDUCATOR / TRAINER / DIGITAL LEARNING CREATOR</p><h1>DESIGNING LEARNING.<br><span>BUILDING<br>POSSIBILITIES.</span></h1><p class="lead">I’m Julie Marlina Hasan. My practice connects English language teaching, educator development and practical digital learning in TVET.</p><div class="studio-actions"><a class="btn" href="#/work">Explore my contributions ↗</a><a class="btn btn-light" href="#/journey">Follow my journey →</a></div></div><figure><img src="assets/julie-camp21.jpg" alt="Julie Marlina Hasan · authentic archive portrait"><figcaption>JULIE MARLINA HASAN · POLITEKNIK PORT DICKSON · ARCHIVE PORTRAIT</figcaption></figure></header><section class="studio-section"><p class="kicker">SELECTED CONTRIBUTIONS</p><h2>THE WORK.<br>THE PEOPLE.</h2><div class="studio-grid">${['y26-acheh','y26-dt-jan7','legacy-0'].map(k=>contributions.find(r=>r.key===k)).filter(Boolean).map(card).join('')}</div></section><section class="studio-section studio-band"><div class="studio-split"><div><p class="kicker">WHAT I BRING</p><h2>IDEAS THAT<br>BECOME PRACTICE.</h2><p class="lead">The classroom remains my starting point. Training, service and collaboration extend that practice to others.</p></div><div>${[['Teaching','English communication, contextual learning and assessment.'],['Capacity building','Workshops, facilitation and educator support.'],['Digital practice','Learning resources and tools shaped around real teaching needs.']].map(r=>`<div class="capability"><b>${r[0]}</b>${r[1]}</div>`).join('')}</div></div></section><section class="studio-section"><p class="kicker">THE JOURNEY FORWARD</p><h2>FOUR CHAPTERS.<br>ONE CONTINUING PRACTICE.</h2><div class="year-grid">${['2023','2024','2025','2026'].map(y=>`<a class="year-tile" href="#/journey/${y}"><b>${y}</b><strong>${({2023:'Share',2024:'Step Up',2025:'Expand',2026:'Converge & Build'})[y]}</strong><span>Enter the chapter ↗</span></a>`).join('')}</div></section><section class="collaborate-block"><h2>LET’S BUILD<br>MEANINGFUL LEARNING.</h2><a class="btn" href="#/contact">Let’s collaborate ↗</a></section>`;
 document.getElementById('view-about').innerHTML=`<header class="studio-hero"><div><p class="kicker">ABOUT / JULIE MARLINA BINTI HASAN</p><h1>I TEACH.<br><span>I CREATE.</span><br>I SHARE.</h1><p class="lead">A lecturer and freelance trainer whose work connects language, learning design and educator development.</p></div><figure><img src="assets/thunkable-02.jpg" alt="Julie facilitating a Thunkable workshop in 2023"><figcaption>Authentic workshop photograph · 2023</figcaption></figure></header><section class="studio-section studio-split"><div><h2>THE EDUCATOR<br>BEHIND THE WORK.</h2></div><div><p>Julie Marlina binti Hasan is a lecturer in Jabatan Pengajian Am at Politeknik Port Dickson, with a TESL background and more than two decades of experience teaching Communicative English and supporting MUET preparation.</p><p>Her practice brings together classroom teaching, educator training, digital learning development, institutional committee service and community engagement. Each contribution is presented with its role, context and available evidence.</p></div></section><section class="studio-section" style="background:#fff"><p class="kicker">TEACHING PHILOSOPHY</p><h2>MAKE LEARNING<br>RELEVANT. MAKE IT ACTIVE.</h2><p class="lead">I connect language learning with situations students recognise: seeking work, making enquiries, presenting ideas and responding to workplace needs.</p><p>I use discussion, practice, reflection and digital resources to help learners participate with purpose. Technology earns its place when it supports that learning.</p></section><section class="studio-section"><h2>EXPERTISE &<br>PROFESSIONAL PRACTICE.</h2><div class="studio-grid">${[['Language teaching','Communicative English · Technical English · MUET support'],['Educator development','Design Thinking · digital teaching workshops · facilitation'],['Learning design','Interactive resources · assessment support · contextual learning'],['Institutional contribution','APACC · UKKP · Strategic Management · curriculum coordination'],['Professional accreditation','HRD Corp Accredited Trainer; source certificate available in Evidence.'],['National contribution','BIPD micro-credential graphic design · JPPKK language review']].map(r=>`<article class="evidence-card"><h3>${r[0]}</h3><p>${r[1]}</p></article>`).join('')}</div><p><a class="btn" href="#/evidence">View professional evidence ↗</a></p></section>`;
 document.getElementById('view-work').innerHTML=`<header class="studio-section"><p class="kicker">CONTRIBUTIONS / THE FULL PRACTICE</p><h1 style="font-size:clamp(60px,9vw,125px)">WORK THAT<br>CONNECTS.</h1><p class="lead">Browse teaching, innovation, scholarship, leadership, training and community contribution across the years.</p><div class="filters" id="contribution-filters"><button data-domain="all" aria-pressed="true">All contributions</button>${Object.entries(labels).map(([k,v])=>`<button data-domain="${k}" aria-pressed="false">${v}</button>`).join('')}<label><span class="kicker">Search contributions</span><br><input type="search" id="contribution-search" placeholder="Programme, role or year"></label></div><p id="contribution-count" class="result-count" aria-live="polite"></p><div id="contribution-grid" class="studio-grid"></div></header>`;
 const main=document.querySelector('main');main.insertAdjacentHTML('beforeend',`<section id="view-contribution" class="view"></section><section id="view-contact" class="view"><header class="studio-hero"><div><p class="kicker">LET’S COLLABORATE</p><h1>LET’S MAKE<br><span>LEARNING<br>MATTER.</span></h1><p class="lead">For educator training, digital learning collaboration and professional sharing.</p></div><figure><img src="assets/thunkable-01.jpg" alt="Julie sharing digital teaching practice in a workshop"><figcaption>Workshop facilitation · archive photograph</figcaption></figure></header><section class="studio-section studio-split"><div><h2>START WITH<br>A CONVERSATION.</h2><p>Share your audience, learning needs and the kind of collaboration you have in mind.</p><a class="btn" href="mailto:juliemarlina@polipd.edu.my?subject=Portfolio%20collaboration">Email Julie ↗</a></div><div>${[['Educator workshops','Digital teaching, Design Thinking and practical learning-resource development.'],['Language learning','English communication and contextual learning experiences.'],['Professional collaboration','Teaching innovation, programme contribution and evidence-based development.']].map(r=>`<div class="contact-choice"><h3>${r[0]}</h3><p>${r[1]}</p></div>`).join('')}</div></section></section>`);
 buildSynthesis();buildEvidence();renderContributions();main.insertAdjacentHTML('afterend',footer+'<dialog class="studio-lightbox" id="studio-lightbox" aria-label="Programme photograph"><button aria-label="Close photograph">Close ×</button><img alt=""><p></p></dialog>');
 let domain='all';document.getElementById('contribution-filters').addEventListener('click',ev=>{const b=ev.target.closest('[data-domain]');if(!b)return;domain=b.dataset.domain;document.querySelectorAll('[data-domain]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));renderContributions(domain);});document.getElementById('contribution-search').oninput=()=>renderContributions(domain);
 document.querySelector('.motion-toggle').onclick=function(){paused=!paused;document.body.classList.toggle('motion-paused',paused);this.setAttribute('aria-pressed',String(paused));this.textContent=paused?'Resume motion':'Pause motion';for(const id of ['chapter-2025','chapter-2026']){let r=document.getElementById(id).shadowRoot;if(r){let s=r.getElementById('motion-state');if(!s){s=document.createElement('style');s.id='motion-state';r.append(s);}s.textContent=paused?'*,*:before,*:after{animation-play-state:paused!important;transition:none!important}':'';}}};
 document.addEventListener('click',ev=>{const b=ev.target.closest('[data-studio-photo]');if(b){const box=document.getElementById('studio-lightbox');box.querySelector('img').src=b.dataset.studioPhoto;box.querySelector('img').alt=b.dataset.caption;box.querySelector('p').textContent=b.dataset.caption;box.showModal();}});const box=document.getElementById('studio-lightbox');box.querySelector('button').onclick=()=>box.close();box.onclick=ev=>{if(ev.target===box){const r=box.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)box.close();}};
 const originalRoute=route;route=function(){const [name,sub]=location.hash.replace(/^#\/?/,'').split('/');if(name==='work'){location.replace('#/evidence');return}if(name==='dh13'&&!window.JM_EDIT){location.href='folio-dh13.html';return}if(name==='contact'||name==='contribution'){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+name).classList.add('active');if(name==='contribution')renderDetail(sub);window.scrollTo(0,0);}else{originalRoute();if(name==='journey'){const overview=!['2023','2024','2025','2026'].includes(sub);document.getElementById('journey-overview').hidden=!overview;document.querySelectorAll('[class^="share202"]').forEach(v=>{if(overview){v.hidden=true;v.style.display='none';}});document.querySelector('.subnav-2023').style.display=!overview&&sub==='2023'?'flex':'none';}}document.querySelectorAll('#main-nav a').forEach(a=>a.setAttribute('aria-current',a.hash===location.hash||name==='contribution'&&a.hash==='#/work'?'page':'false'));document.querySelector('#main-nav').classList.remove('is-open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false');};
 // Replace the previous registered route callback so it cannot reset new detail/contact pages.
 removeEventListener('hashchange',originalRoute);addEventListener('hashchange',route);route();
 document.querySelectorAll('.subnav-2023 a[href^="#"]').forEach(a=>a.onclick=ev=>{ev.preventDefault();document.getElementById(a.hash.slice(1))?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});});
}
function renderContributions(domain='all'){const q=document.getElementById('contribution-search')?.value.trim().toLowerCase()||'';const list=contributions.filter(r=>(domain==='all'||r.domain===domain)&&[r.title,r.role,r.year].join(' ').toLowerCase().includes(q));document.getElementById('contribution-grid').innerHTML=list.length?list.map(card).join(''):'<p class="empty">No contributions match. Try another role or programme.</p>';document.getElementById('contribution-count').textContent=list.length+' contribution records';}
function renderDetail(key){const r=contributions.find(r=>r.key===key),host=document.getElementById('view-contribution');if(!r){host.innerHTML='<section class="studio-section"><h1>Contribution not found</h1><a href="#/work">Return to contributions</a></section>';return;}
const confirmed=/confirmed|disahkan|certificate|VERIFIED|Appointment/i.test(r.status||'');const reflection=({pdp:'This contribution connects teaching responsibilities with the learning experience I design for students.',sumb:'This contribution places professional practice in a wider institutional, community and national context.',lead:'This responsibility shows the leadership work that supports programmes, colleagues and institutional practice.',diri:'This record marks a step in my continuing professional development.',rdci:'This contribution connects innovation and research with everyday teaching practice.'})[r.domain]||'';
host.innerHTML=`<header class="detail-hero"><a href="#/work">← All contributions</a><p class="kicker">${e(crit(r))} / ${e(r.year)}</p><h1>${e(r.title)}</h1><p class="lead">${e(r.role)}</p><span class="tag">${e(r.date||r.year)}</span><span class="tag">${e(/VERIFIED/.test(r.status||'')?'Verified record':(r.status||'Source record'))}</span></header><section class="studio-section detail-layout"><aside><p class="kicker">MY ROLE</p><div class="detail-role"><strong>${e(r.role)}</strong><p>${e(r.date||r.year)}</p></div><p><a class="btn" href="#/journey/${r.year}">Explore ${e(r.year)} chapter →</a></p></aside><div><p class="kicker">WHAT I CONTRIBUTED / SOURCE CONTEXT</p><h2>THE WORK<br>IN CONTEXT.</h2><p>${e(r.note||'The available source establishes the contribution recorded here. Read the evidence for the full context.')}</p>${r.related?`<a class="btn" href="${e(r.related)}" target="_blank" rel="noopener">Explore learning resource ↗</a>`:''}${key==='y26-role-6'?'<a class="btn" href="2026-smart-dt-camp21.html">Explore Smart DT / CAMP21 learning design ↗</a>':''}</div></section>${r.photos.length?`<section class="studio-section" style="background:white"><p class="kicker">PHOTO GALLERY / SOURCE VISUALS</p><h2>FROM THE<br>PROGRAMME.</h2><div class="detail-gallery">${r.photos.map(p=>`<figure><button class="photo-open" data-studio-photo="${e(p.src)}" data-caption="${e(p.caption)}"><img src="${e(p.src)}" alt="${e(p.caption)}" loading="lazy"></button><figcaption>${e(p.caption)}${p.source?` · <a href="${e(p.source)}" target="_blank" rel="noopener">Source ↗</a>`:''}</figcaption></figure>`).join('')}</div></section>`:''}${window.JM_EDIT&&r.audit?`<section class="studio-section owner-note"><p class="kicker">OWNER NOTE · NOT PUBLIC</p><p>${e(r.audit)}</p></section>`:''}<section class="studio-section studio-band"><p class="kicker">EVIDENCE & CROSS-REFERENCES</p><h2>FOLLOW<br>THE SOURCE.</h2><div class="studio-actions">${r.url?`<a class="btn btn-light" href="${e(r.url)}" target="_blank" rel="noopener">Open primary evidence ↗</a>`:''}<a class="btn btn-light" href="folio-dh13.html#${r.domain}">See this criterion in the DH13 Folio ↗</a><a class="btn btn-light" href="#/evidence">Portfolio evidence archive →</a></div></section><section class="studio-section"><p class="kicker">REFLECTION</p><h2>THE PRACTICE<br>CONTINUES.</h2><p class="lead">${reflection}</p><a href="#/work">Explore another contribution →</a></section>`;
}
function buildSynthesis(){document.getElementById('view-dh13').innerHTML=`<header class="studio-section"><p class="kicker">DH13 / ASSESSOR CROSS-REFERENCES</p><h1 style="font-size:clamp(55px,8vw,110px)">THE JOURNEY.<br>THE EVIDENCE.</h1><p class="lead">A synthesis of contribution, supporting records and remaining validation needs.</p><p>Current-grade evidence begins on 5 February 2024. Earlier chapters show professional progression. A confirmed role does not automatically establish acceptance under a promotion criterion.</p><a class="btn" href="${sheet}" target="_blank" rel="noopener">Open the live DH13 tracker ↗</a></header><section class="studio-section" style="background:white"><div class="table-scroll"><table class="studio-table"><thead><tr><th>Tracker area</th><th>Supported contribution</th><th>Evidence & cross-reference</th><th>Remaining work</th></tr></thead><tbody>${[
['T1 / K4 · Teaching & coordination','TESL SME CE2; CE3 Course Coordinator; LI monitoring','y26-role-11','Confirm teaching, CQI and observation records; reconcile CE2 course code.'],['T3 / T4 · Innovation & research','Smart MUET Guide V2 project leadership','smart-muet','Permission request is not completed testing. Full research report, actual data and institutional validation remain separate.'],['K1 · Strategic management','Data & Information Secretariat, Strategic Management','y26-role-2','Reconcile June revision; add individual outputs and KPI/SKU evidence. HRMIS letter does not name Julie.'],['K2 · Research leadership','Principal Research Officer, Smart MUET Guide V2','smart-muet','Project leadership is supported; departmental leadership criterion needs validation.'],['K3 · Scholarly committee — candidate','JPPKK Engineering Science language review','y26-role-13','Review appointment and output exist; acceptance as publication committee criterion needs validation.'],['S1 · Institutional contribution','APACC C7 Secretary; UKKP Secretary; NBIC and convocation committees','y26-role-0','Check role duplication, main duties and completion evidence before counting.'],['S2 · External/community contribution','Acheh volunteer contribution; CAMP21 Head of Speakers; SOLS appointment','y26-acheh','SOLS appointment is separate from completed programme evidence; eligibility and totals require validation.'],['T6 · Presentation candidate','BIPD Future-Ready AI panel-speaker appointment','gemini-webinar','Recording schedule supports appointment; acceptance as seminar/conference presentation is unresolved.']].map(r=>`<tr><td><strong>${r[0]}</strong></td><td>${r[1]}</td><td><a href="#/contribution/${r[2]}">Inspect contribution ↗</a><br><a href="${sheet}#gid=1120083816" target="_blank" rel="noopener">TRACKER ↗</a></td><td>${r[3]}</td></tr>`).join('')}</tbody></table></div><p class="notice">Evidence counts and formal completion status follow the live Google Sheet. This portfolio does not independently award promotion points.</p></section>`;}
function buildEvidence(){const host=document.getElementById('view-evidence');host.innerHTML=`<header class="studio-section"><p class="kicker">EVIDENCE / INSPECTABLE SOURCES</p><h1 style="font-size:clamp(55px,8vw,110px)">THE RECORD<br>BEHIND THE WORK.</h1><p>Search by programme or role. Filter by year, promotion criterion and evidence type.</p><div class="filters"><label>Search<br><input id="archive-search" type="search" placeholder="Programme or role"></label><label>Year<br><select id="archive-year"><option value="all">All years</option>${['2023','2024','2025','2026'].map(y=>`<option>${y}</option>`).join('')}</select></label><label>Criterion<br><select id="archive-domain"><option value="all">All five criteria</option>${Object.entries(labels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>Evidence type<br><select id="archive-type"><option value="all">All source types</option><option value="appointment">Appointment / nomination</option><option value="certificate">Certificate / recognition</option><option value="output">Report / publication / output</option><option value="planning">Planning / roadmap</option><option value="other">Supporting source</option></select></label></div><p id="archive-count" class="result-count" aria-live="polite"></p><p><a href="folio-dh13.html">Open the DH13 Folio ↗</a></p><div id="archive-results" class="studio-grid"></div></header>`;
function kind(r){const s=(r.type||r.status||'').toLowerCase();if(/roadmap|planning|proposal|working paper/.test(s))return'planning';if(/appointment|nomination|pelantikan/.test(s))return'appointment';if(/certificate|recognition/.test(s))return'certificate';if(/report|publication|published|output|proceedings/.test(s))return'output';return'other';}
function draw(){const q=document.getElementById('archive-search').value.trim().toLowerCase(),year=document.getElementById('archive-year').value,domain=document.getElementById('archive-domain').value,type=document.getElementById('archive-type').value;const list=contributions.filter(r=>(year==='all'||r.year===year)&&(domain==='all'||r.domain===domain)&&(type==='all'||kind(r)===type)&&[r.title,r.role].join(' ').toLowerCase().includes(q));document.getElementById('archive-count').textContent=list.length+' source records';document.getElementById('archive-results').innerHTML=list.length?list.map(r=>`<article class="evidence-card"><span class="tag">${r.year}</span><p class="kicker">${e(crit(r))}</p><h3>${e(r.title)}</h3><p><strong>${e(r.role)}</strong></p><p>${e(r.type||r.status||'Source record')}</p><a href="#/contribution/${r.key}">Read context →</a>${r.url?` · <a href="${e(r.url)}" target="_blank" rel="noopener">Source ↗</a>`:''}</article>`).join(''):'<p class="empty">No matching evidence. Try broader filters.</p>';}
['archive-search','archive-year','archive-domain','archive-type'].forEach(id=>document.getElementById(id).addEventListener(id==='archive-search'?'input':'change',draw));draw();}
document.addEventListener('DOMContentLoaded',init);
})();
